apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wwttestapp
  namespace: flux-system
spec:
  interval: 60s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default